### ISSUE TITLE
Impound  spawnpoint issue

### ISSUE THREAD

**Issue by Jonneis** [lukman-nov/kc_garage#2]
If you  have already another vehicle on the position and you pay to get another vehicle from the impount then it takes the money but it doesnt spawn the car.

Reproduce steps:
1. Go to Impound and pay to spawn a car.
2. Pay to spawn another one (without to move the first).
3. It gets the money but it doesnt spawn the car.

**Comment by lukman-nov** [comment]
thanks, I'll fix this
